"""HTML renderer — emits the buyer-report skeleton.

Reads the payload dict produced by `payload.py`, returns a single
self-contained HTML string. Per-card prose is left as a marker
(`<!-- prose:{asin} -->`) for downstream injection.

PRD §5 is the contract.
"""
from __future__ import annotations

import html as _html
from typing import Any


_TOC_MIN_ROWS = 4   # PRD §5.4 — TOC omitted for ≤3 actionable rows


_VERDICT_TO_SECTION = [
    ("BUY", "section-buy", "Why we should buy"),
    ("SOURCE_ONLY", "section-source-only", "Why source this"),
    ("NEGOTIATE", "section-negotiate", "Why negotiate"),
    ("WATCH", "section-watch", "Why watch"),
]


def render_html(payload: dict) -> str:
    """Render the full buyer-report HTML from a payload dict."""
    rows = payload.get("rows") or []
    counts = payload.get("verdict_counts") or {}
    strategy = payload.get("strategy") or ""
    supplier = payload.get("supplier")
    run_id = payload.get("run_id") or ""
    title_suffix = supplier if supplier else strategy
    title = f"Buyer Report — {title_suffix} — {run_id}"

    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        f"<title>{_esc(title)}</title>",
        f"<style>{_CSS}</style>",
        "</head>",
        "<body>",
        _render_header(payload),
    ]

    if len(rows) >= _TOC_MIN_ROWS:
        parts.append(_render_toc(rows))

    parts.append("<main>")
    if not rows:
        parts.append('<div class="empty-notice">No actionable rows in this run.</div>')
    else:
        for verdict, section_id, _heading in _VERDICT_TO_SECTION:
            section_rows = [r for r in rows if (r.get("verdict") or "").upper() == verdict]
            if not section_rows:
                continue
            section_rows = _sort_within_verdict(verdict, section_rows)
            parts.append(f'<section id="{section_id}" class="verdict-section">')
            count = counts.get(verdict, len(section_rows))
            parts.append(f"<h2>{verdict} ({count})</h2>")
            for row in section_rows:
                parts.append(_render_card(row))
            parts.append("</section>")
    parts.append("</main>")

    parts.append(_render_footer(payload))
    parts.append("</body></html>")
    return "\n".join(parts)


def _sort_within_verdict(verdict: str, rows: list[dict]) -> list[dict]:
    """PRD §5.4 — BUY by projected_30d_profit desc; others by opportunity_score desc."""
    if verdict == "BUY":
        return sorted(
            rows,
            key=lambda r: -(r.get("buy_plan", {}).get("projected_30d_profit_gbp") or 0),
        )
    return sorted(rows, key=lambda r: -(r.get("opportunity_score") or 0))


def _render_header(payload: dict) -> str:
    counts = payload.get("verdict_counts") or {}
    strategy = payload.get("strategy") or ""
    supplier = payload.get("supplier")
    title_suffix = supplier if supplier else strategy
    chips = " ".join(
        f'<span class="vc vc-{v.lower().replace("_","-")}">{v} {counts.get(v, 0)}</span>'
        for v in ("BUY", "SOURCE_ONLY", "NEGOTIATE", "WATCH")
    )
    return (
        '<header class="report-header">'
        f"<h1>Buyer Report</h1>"
        f'<div class="run-meta">{_esc(title_suffix)} · run {_esc(payload.get("run_id") or "")}</div>'
        f'<div class="verdict-counts">{chips}</div>'
        "</header>"
    )


def _render_footer(payload: dict) -> str:
    return (
        "<footer>"
        f"<div>Generated by 09_buy_plan_html · {_esc(payload.get('generated_at') or '')}</div>"
        "</footer>"
    )


def _render_toc(rows: list[dict]) -> str:
    parts = ['<nav class="toc"><h3>Contents</h3>']
    for verdict, section_id, _heading in _VERDICT_TO_SECTION:
        section_rows = [r for r in rows if (r.get("verdict") or "").upper() == verdict]
        if not section_rows:
            continue
        parts.append(
            f'<div class="toc-section"><a href="#{section_id}">{verdict} ({len(section_rows)})</a><ul>'
        )
        for r in _sort_within_verdict(verdict, section_rows):
            asin = r.get("asin") or ""
            title = r.get("title") or asin
            parts.append(
                f'<li><a href="#asin-{_esc(asin)}">{_esc(title[:50])}</a></li>'
            )
        parts.append("</ul></div>")
    parts.append("</nav>")
    return "".join(parts)


def _render_card(row: dict) -> str:
    asin = row.get("asin") or ""
    verdict = (row.get("verdict") or "").upper()
    cls = f"verdict-{verdict.lower().replace('_','-')}"
    return (
        f'<article id="asin-{_esc(asin)}" class="card {cls}">'
        f"{_render_card_header(row)}"
        f'<div class="card-identity-economics">'
        f"{_render_image(row)}"
        f'<div class="card-summary">{_render_summary(row)}{_render_economics_grid(row)}</div>'
        f"</div>"
        f"{_render_prose_section(row)}"
        f"{_render_scoring(row)}"
        f"{_render_next_action(row)}"
        f"</article>"
    )


def _render_card_header(row: dict) -> str:
    verdict = row.get("verdict") or ""
    confidence = row.get("verdict_confidence") or ""
    score = row.get("opportunity_score")
    score_str = f"Score: {int(score)}/100" if score is not None else ""
    return (
        '<header class="card-header">'
        f'<span class="verdict-badge">{_esc(verdict)} · {_esc(confidence)}</span>'
        f'<span class="card-score">{_esc(score_str)}</span>'
        "</header>"
    )


def _render_image(row: dict) -> str:
    asin = row.get("asin") or ""
    image_url = row.get("image_url") or ""
    amazon_url = row.get("amazon_url") or "#"
    title = row.get("title") or asin
    return (
        f'<a class="card-image" href="{_esc(amazon_url)}" target="_blank" rel="noopener">'
        f'<img src="{_esc(image_url)}" '
        f'onerror="this.style.display=\'none\'" '
        f'alt="{_esc(title)}" loading="lazy">'
        "</a>"
    )


def _render_summary(row: dict) -> str:
    asin = row.get("asin") or ""
    title = row.get("title") or asin
    brand = row.get("brand") or ""
    amazon_url = row.get("amazon_url") or ""
    return (
        f'<h3 class="card-title">{_esc(title)}</h3>'
        f'<div class="card-id">ASIN <a href="{_esc(amazon_url)}">{_esc(asin)}</a> · Brand {_esc(brand)}</div>'
    )


def _render_economics_grid(row: dict) -> str:
    verdict = (row.get("verdict") or "").upper()
    eco = row.get("economics") or {}
    bp = row.get("buy_plan") or {}

    def gbp(v):
        return f"£{float(v):.2f}" if v is not None else "—"

    def num(v, suffix=""):
        return f"{float(v):.0f}{suffix}" if v is not None else "—"

    def units_and_gbp(units, gbp_val):
        # "{N} units · £X.XX" — keeps revenue/profit visually tied to
        # the unit count that produced it. Falls back gracefully when
        # either is None.
        if gbp_val is None:
            return "—"
        cash = f"£{float(gbp_val):.2f}"
        if units is None:
            return cash
        return f"{int(float(units))} units · {cash}"

    units = bp.get("projected_30d_units")

    if verdict == "BUY":
        return (
            '<table class="economics-grid"><tbody>'
            f'<tr><td class="econ-label">Buy cost</td><td class="econ-value">{gbp(eco.get("buy_cost_gbp"))}</td>'
            f'<td class="econ-label">Target buy</td><td class="econ-value">{gbp(eco.get("target_buy_cost_gbp"))} (stretch {gbp(eco.get("target_buy_cost_stretch_gbp"))})</td></tr>'
            f'<tr><td class="econ-label">Order qty</td><td class="econ-value">{num(bp.get("order_qty_recommended"))}</td>'
            f'<td class="econ-label">Capital</td><td class="econ-value">{gbp(bp.get("capital_required_gbp"))}</td></tr>'
            f'<tr><td class="econ-label">Payback</td><td class="econ-value">{num(bp.get("payback_days"))} days</td>'
            f'<td class="econ-label">30d profit</td><td class="econ-value">{units_and_gbp(units, bp.get("projected_30d_profit_gbp"))}</td></tr>'
            "</tbody></table>"
        )
    if verdict == "SOURCE_ONLY":
        return (
            '<table class="economics-grid"><tbody>'
            f'<tr><td class="econ-label">Buy cost</td><td class="econ-value">— (no supplier yet)</td>'
            f'<td class="econ-label">Target buy</td><td class="econ-value">≤ {gbp(eco.get("target_buy_cost_gbp"))} (stretch {gbp(eco.get("target_buy_cost_stretch_gbp"))})</td></tr>'
            f'<tr><td class="econ-label">Projected 30d revenue</td><td class="econ-value">{units_and_gbp(units, bp.get("projected_30d_revenue_gbp"))}</td>'
            f'<td class="econ-label">30d profit at target</td><td class="econ-value">{gbp(bp.get("projected_30d_profit_gbp"))}</td></tr>'
            "</tbody></table>"
        )
    if verdict == "NEGOTIATE":
        gap_gbp = bp.get("gap_to_buy_gbp")
        gap_pct = bp.get("gap_to_buy_pct")
        gap_str = f"{gbp(gap_gbp)} ({float(gap_pct):.1%})" if gap_pct is not None else gbp(gap_gbp)
        return (
            '<table class="economics-grid"><tbody>'
            f'<tr><td class="econ-label">Currently</td><td class="econ-value">{gbp(eco.get("buy_cost_gbp"))}</td>'
            f'<td class="econ-label">Target ceiling</td><td class="econ-value">{gbp(eco.get("target_buy_cost_gbp"))} (stretch {gbp(eco.get("target_buy_cost_stretch_gbp"))})</td></tr>'
            f'<tr><td class="econ-label">Gap to BUY</td><td class="econ-value gap-positive">{gap_str}</td>'
            f'<td class="econ-label">30d profit (current)</td><td class="econ-value">{units_and_gbp(units, bp.get("projected_30d_profit_gbp"))}</td></tr>'
            "</tbody></table>"
        )
    # WATCH
    return (
        '<table class="economics-grid"><tbody>'
        f'<tr><td class="econ-label">Buy cost</td><td class="econ-value">{gbp(eco.get("buy_cost_gbp"))}</td>'
        f'<td class="econ-label">Target buy</td><td class="econ-value">{gbp(eco.get("target_buy_cost_gbp"))} (stretch {gbp(eco.get("target_buy_cost_stretch_gbp"))})</td></tr>'
        f'<tr><td class="econ-label">Projected 30d revenue</td><td class="econ-value">{units_and_gbp(units, bp.get("projected_30d_revenue_gbp"))}</td>'
        f'<td class="econ-label">30d profit</td><td class="econ-value">{gbp(bp.get("projected_30d_profit_gbp"))}</td></tr>'
        "</tbody></table>"
    )


def _render_prose_section(row: dict) -> str:
    verdict = (row.get("verdict") or "").upper()
    headings = {
        "BUY": "Why we should buy",
        "SOURCE_ONLY": "Why source this",
        "NEGOTIATE": "Why negotiate",
        "WATCH": "Why watch",
    }
    asin = row.get("asin") or ""
    return (
        '<section class="card-prose">'
        f"<h4>{_esc(headings.get(verdict, 'Notes'))}</h4>"
        f'<div class="prose" data-asin="{_esc(asin)}"><!-- prose:{asin} --></div>'
        "</section>"
    )


def _render_scoring(row: dict) -> str:
    metrics = row.get("metrics") or []
    if not metrics:
        return ""
    rows = []
    for m in metrics:
        v = m.get("verdict") or "grey"
        cls = f"dot dot-{v}"
        rows.append(
            f'<tr>'
            f'<td><span class="{cls}"></span></td>'
            f'<td class="metric-label">{_esc(m.get("label") or "")}</td>'
            f'<td class="metric-value">{_esc(m.get("value_display") or "")}</td>'
            f'<td class="metric-rationale">{_esc(m.get("rationale") or "")}</td>'
            "</tr>"
        )
    return (
        '<section class="card-scoring"><h4>Scoring</h4>'
        '<table class="metrics"><tbody>' + "".join(rows) + "</tbody></table>"
        "</section>"
    )


def _render_next_action(row: dict) -> str:
    na = row.get("next_action") or ""
    if not na:
        return ""
    return f'<footer class="card-next-action"><strong>Next action:</strong> {_esc(na)}</footer>'


def _esc(s: Any) -> str:
    return _html.escape(str(s if s is not None else ""))


_CSS = """
:root {
  --buy: #27AE60; --source: #2980B9; --negotiate: #E67E22; --watch: #F1C40F;
  --grey: #B0B0B0; --green: #27AE60; --amber: #E67E22; --red: #C0392B;
}
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1B2A4A; max-width: 1280px; margin: 0 auto; padding: 1rem; }
.report-header { padding: 1rem; border-bottom: 1px solid #ddd; }
.report-header h1 { margin: 0; }
.run-meta { color: #666; font-size: 0.9rem; }
.verdict-counts { margin-top: 0.5rem; }
.vc { display: inline-block; padding: 0.2rem 0.6rem; margin-right: 0.4rem; border-radius: 3px; font-size: 0.85rem; color: white; font-weight: bold; }
.vc-buy { background: var(--buy); }
.vc-source-only { background: var(--source); }
.vc-negotiate { background: var(--negotiate); }
.vc-watch { background: var(--watch); color: #1B2A4A; }
.toc { padding: 1rem; background: #f8f9fa; border-radius: 4px; margin: 1rem 0; }
.toc h3 { margin-top: 0; }
.toc ul { margin: 0; padding-left: 1.2rem; font-size: 0.9rem; }
.empty-notice { padding: 2rem; text-align: center; color: #666; }
.verdict-section { margin: 2rem 0; }
.card { border: 1px solid #ddd; border-left: 4px solid #ddd; border-radius: 4px; padding: 1rem; margin: 1rem 0; max-width: 900px; }
.verdict-buy { border-left-color: var(--buy); }
.verdict-source-only { border-left-color: var(--source); }
.verdict-negotiate { border-left-color: var(--negotiate); }
.verdict-watch { border-left-color: var(--watch); }
.card-header { display: flex; justify-content: space-between; align-items: center; }
.verdict-badge { font-weight: bold; padding: 0.2rem 0.6rem; border-radius: 3px; background: #1B2A4A; color: white; }
.verdict-buy .verdict-badge { background: var(--buy); }
.verdict-source-only .verdict-badge { background: var(--source); }
.verdict-negotiate .verdict-badge { background: var(--negotiate); }
.verdict-watch .verdict-badge { background: var(--watch); color: #1B2A4A; }
.card-score { color: #666; font-size: 0.9rem; }
.card-identity-economics { display: flex; gap: 1rem; margin: 1rem 0; }
.card-image img { width: 200px; height: auto; max-width: 100%; object-fit: contain; }
.card-summary { flex: 1; }
.card-title { margin: 0 0 0.5rem 0; }
.card-id { color: #666; font-size: 0.9rem; margin-bottom: 0.8rem; }
.economics-grid { width: 100%; border-collapse: collapse; font-size: 0.95rem; }
.economics-grid td { padding: 0.4rem; vertical-align: top; }
.econ-label { color: #666; font-size: 0.85rem; width: 25%; }
.econ-value { font-weight: bold; }
.gap-positive { color: var(--red); }
.card-prose { padding: 0.5rem 0; }
.card-prose h4 { margin: 0.5rem 0 0.3rem 0; font-size: 1rem; }
.prose { color: #1B2A4A; line-height: 1.5; }
.card-scoring { margin: 1rem 0; }
.card-scoring h4 { margin: 0 0 0.4rem 0; font-size: 1rem; }
.metrics { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
.metrics td { padding: 0.3rem 0.5rem; vertical-align: middle; }
.dot { width: 14px; height: 14px; border-radius: 50%; display: inline-block; }
.dot-green { background: var(--green); }
.dot-amber { background: var(--amber); }
.dot-red { background: var(--red); }
.dot-grey { background: transparent; border: 1.5px solid var(--grey); }
.metric-label { width: 30%; }
.metric-value { font-weight: bold; width: 15%; }
.metric-rationale { color: #666; font-size: 0.85rem; }
.card-next-action { padding-top: 0.6rem; border-top: 1px solid #eee; font-size: 0.95rem; }
footer { margin-top: 2rem; color: #999; font-size: 0.85rem; }
@media print {
  .toc { display: none; }
  .card { page-break-inside: avoid; }
  body { background: white; }
}
"""
