"""HTML renderer — emits the buyer-report card view.

Reads the payload dict produced by `payload.py` (with analyst block
populated by `analyst.py` or Cowork orchestration). Returns a
single self-contained HTML string.

Card hierarchy (per the brainstorm result):
    1. Verdict badge + score + 4-dim breakdown bars (header)
    2. Buyer's read — narrative + action prompt (lead the card)
    3. Direction — sales/sellers/price arrows + trend story
    4. Economics — fixed labels: "Aim for X" / "Don't exceed Y"
    5. Supporting metrics — 7-row traffic-light table (demoted to bottom)
    6. Engine note (small print: engine's own verdict, blockers)
"""
from __future__ import annotations

import html as _html
from typing import Any


_TOC_MIN_ROWS = 4

# Analyst-verdict taxonomy (Q4 — buyer-action shaped).
_ANALYST_VERDICT_TO_SECTION = [
    ("BUY",       "section-buy",       "Why BUY"),
    ("NEGOTIATE", "section-negotiate", "Why NEGOTIATE"),
    ("SOURCE",    "section-source",    "Why SOURCE"),
    ("WAIT",      "section-wait",      "Why WAIT"),
    ("SKIP",      "section-skip",      "Why SKIP"),
]

_ANALYST_VERDICT_LABELS = {v[0]: v[2] for v in _ANALYST_VERDICT_TO_SECTION}


def render_html(payload: dict) -> str:
    rows = payload.get("rows") or []
    strategy = payload.get("strategy") or ""
    supplier = payload.get("supplier")
    run_id = payload.get("run_id") or ""
    title_suffix = supplier if supplier else strategy
    title = f"Buyer Report — {title_suffix} — {run_id}"

    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        f"<title>{_esc(title)}</title>",
        f"<style>{_CSS}</style>",
        "</head>",
        "<body>",
        _render_header(payload),
    ]
    if len(rows) >= _TOC_MIN_ROWS:
        parts.append(_render_toc(rows))

    parts.append("<main>")
    if not rows:
        parts.append('<div class="empty-notice">No actionable rows in this run.</div>')
    else:
        for verdict, section_id, _heading in _ANALYST_VERDICT_TO_SECTION:
            section_rows = [
                r for r in rows
                if (_analyst_verdict(r) or "").upper() == verdict
            ]
            if not section_rows:
                continue
            section_rows = _sort_within_verdict(verdict, section_rows)
            parts.append(f'<section id="{section_id}" class="verdict-section">')
            parts.append(f"<h2>{verdict} ({len(section_rows)})</h2>")
            for row in section_rows:
                parts.append(_render_card(row))
            parts.append("</section>")
    parts.append("</main>")

    parts.append(_render_footer(payload))
    parts.append("</body></html>")
    return "\n".join(parts)


def _analyst_verdict(row: dict) -> str | None:
    return _safe_get(row, "analyst", "verdict")


def _safe_get(d: dict, *path: str, default: Any = None) -> Any:
    cur = d
    for k in path:
        if not isinstance(cur, dict) or k not in cur:
            return default
        cur = cur[k]
    return cur


def _sort_within_verdict(verdict: str, rows: list[dict]) -> list[dict]:
    """BUY rows lead by projected_30d_profit desc; others by analyst score."""
    if verdict == "BUY":
        return sorted(
            rows,
            key=lambda r: -(r.get("buy_plan", {}).get("projected_30d_profit_gbp") or 0),
        )
    return sorted(rows, key=lambda r: -(_safe_get(r, "analyst", "score", default=0) or 0))


def _render_header(payload: dict) -> str:
    rows = payload.get("rows") or []
    # Re-count by analyst verdict (engine counts are by engine_verdict).
    counts = {v[0]: 0 for v in _ANALYST_VERDICT_TO_SECTION}
    for r in rows:
        v = (_analyst_verdict(r) or "").upper()
        if v in counts:
            counts[v] += 1
    strategy = payload.get("strategy") or ""
    supplier = payload.get("supplier")
    title_suffix = supplier if supplier else strategy
    chips = " ".join(
        f'<span class="vc vc-{v.lower()}">{v} {counts[v]}</span>'
        for v, _, _ in _ANALYST_VERDICT_TO_SECTION
    )
    return (
        '<header class="report-header">'
        f"<h1>Buyer Report</h1>"
        f'<div class="run-meta">{_esc(title_suffix)} · run {_esc(payload.get("run_id") or "")}</div>'
        f'<div class="verdict-counts">{chips}</div>'
        '<div class="vat-note">All prices inc-VAT</div>'
        "</header>"
    )


def _render_footer(payload: dict) -> str:
    return (
        "<footer>"
        f"<div>Generated by 09_buy_plan_html · {_esc(payload.get('generated_at') or '')}</div>"
        "</footer>"
    )


def _render_toc(rows: list[dict]) -> str:
    parts = ['<nav class="toc"><h3>Contents</h3>']
    for verdict, section_id, _heading in _ANALYST_VERDICT_TO_SECTION:
        section_rows = [
            r for r in rows
            if (_analyst_verdict(r) or "").upper() == verdict
        ]
        if not section_rows:
            continue
        parts.append(
            f'<div class="toc-section"><a href="#{section_id}">{verdict} ({len(section_rows)})</a><ul>'
        )
        for r in _sort_within_verdict(verdict, section_rows):
            asin = r.get("asin") or ""
            ttl = r.get("title") or asin
            parts.append(
                f'<li><a href="#asin-{_esc(asin)}">{_esc(ttl[:50])}</a></li>'
            )
        parts.append("</ul></div>")
    parts.append("</nav>")
    return "".join(parts)


def _render_card(row: dict) -> str:
    asin = row.get("asin") or ""
    verdict = (_analyst_verdict(row) or "WAIT").upper()
    cls = f"verdict-{verdict.lower()}"
    return (
        f'<article id="asin-{_esc(asin)}" class="card {cls}">'
        f"{_render_card_header(row)}"
        f"{_render_dimension_bars(row)}"
        f"{_render_buyers_read(row)}"
        f"{_render_direction(row)}"
        f"{_render_identity_economics(row)}"
        f"{_render_supporting_metrics(row)}"
        f"{_render_engine_note(row)}"
        f"</article>"
    )


def _render_card_header(row: dict) -> str:
    asin = row.get("asin") or ""
    title = row.get("title") or asin
    brand = row.get("brand") or ""
    amazon_url = row.get("amazon_url") or "#"
    image_url = row.get("image_url") or ""

    verdict = (_analyst_verdict(row) or "WAIT").upper()
    confidence = _safe_get(row, "analyst", "verdict_confidence") or ""
    score = _safe_get(row, "analyst", "score")
    score_str = f"{int(score)}/100" if score is not None else "—"

    return (
        '<header class="card-header">'
        f'<a class="card-image" href="{_esc(amazon_url)}" target="_blank" rel="noopener">'
        f'<img src="{_esc(image_url)}" '
        f'onerror="this.style.display=\'none\'" '
        f'alt="{_esc(title)}" loading="lazy"></a>'
        '<div class="card-id-block">'
        f'<h3 class="card-title">{_esc(title)}</h3>'
        f'<div class="card-id">ASIN <a href="{_esc(amazon_url)}">{_esc(asin)}</a> · Brand {_esc(brand)}</div>'
        '</div>'
        '<div class="card-verdict-block">'
        f'<div class="verdict-badge">{_esc(verdict)}</div>'
        f'<div class="verdict-confidence">{_esc(confidence)} confidence</div>'
        f'<div class="card-score">Score <strong>{_esc(score_str)}</strong></div>'
        '</div>'
        "</header>"
    )


def _render_dimension_bars(row: dict) -> str:
    """4-row table: Profit / Competition / Stability / Operational.

    Each row has a horizontal bar + score + rationale. The bar is a
    pure-CSS div with width = score/max %.
    """
    dims = _safe_get(row, "analyst", "dimensions") or []
    if not dims:
        return ""
    rows_html = []
    for d in dims:
        score = d.get("score", 0)
        max_score = d.get("max", 25) or 25
        pct = max(0, min(100, int(100 * score / max_score)))
        verdict_class = (
            "dim-strong" if pct >= 60
            else "dim-ok" if pct >= 30
            else "dim-weak"
        )
        rows_html.append(
            '<tr>'
            f'<td class="dim-name">{_esc(d.get("name", ""))}</td>'
            f'<td class="dim-score">{int(score)}<span class="dim-max">/{int(max_score)}</span></td>'
            f'<td class="dim-bar-cell"><div class="dim-bar {verdict_class}" style="width:{pct}%"></div></td>'
            f'<td class="dim-rationale">{_esc(d.get("rationale", ""))}</td>'
            '</tr>'
        )
    return (
        '<section class="card-dimensions">'
        '<h4>Score breakdown</h4>'
        '<table class="dimensions"><tbody>' + "".join(rows_html) + "</tbody></table>"
        "</section>"
    )


def _render_buyers_read(row: dict) -> str:
    """Narrative paragraph + action prompt — leads the card."""
    narrative = _safe_get(row, "analyst", "narrative") or ""
    action = _safe_get(row, "analyst", "action_prompt") or ""
    if not narrative and not action:
        return ""
    parts = ['<section class="card-buyers-read">']
    parts.append("<h4>Buyer's read</h4>")
    if narrative:
        parts.append(f'<p class="buyers-narrative">{_esc(narrative)}</p>')
    if action:
        parts.append(
            f'<p class="buyers-action"><strong>Next step:</strong> {_esc(action)}</p>'
        )
    parts.append("</section>")
    return "".join(parts)


def _render_direction(row: dict) -> str:
    """3 trend arrows + 1-line synthesis."""
    arrows = _safe_get(row, "analyst", "trend_arrows") or {}
    story = _safe_get(row, "analyst", "trend_story") or ""
    if not arrows and not story:
        return ""

    def cell(name: str, arrow: str) -> str:
        cls = (
            "arrow-up" if arrow == "↗"
            else "arrow-down" if arrow == "↘"
            else "arrow-flat" if arrow == "→"
            else "arrow-unknown"
        )
        return (
            '<div class="dir-cell">'
            f'<div class="dir-label">{_esc(name)}</div>'
            f'<div class="dir-arrow {cls}">{_esc(arrow or "?")}</div>'
            '</div>'
        )

    return (
        '<section class="card-direction">'
        '<h4>Direction (90d)</h4>'
        '<div class="dir-grid">'
        + cell("Sales", arrows.get("sales") or "?")
        + cell("Sellers", arrows.get("sellers") or "?")
        + cell("Price", arrows.get("price") or "?")
        + '</div>'
        + (f'<p class="dir-story">{_esc(story)}</p>' if story else "")
        + "</section>"
    )


def _render_identity_economics(row: dict) -> str:
    """Economics block — re-labelled per Q2 brainstorm:

    'Aim for £X' (stretch target) / "Don't exceed £Y" (BUY ceiling).
    Plus the live cost (where present) and projected 30d numbers.
    """
    eco = row.get("economics") or {}
    bp = row.get("buy_plan") or {}

    def gbp(v):
        # Reject None / NaN — the renderer is also invoked from cli.py
        # against arbitrary on-disk JSON, so float(NaN):.2f → "nan (inc)"
        # would slip through without this guard.
        if v is None:
            return "—"
        try:
            n = float(v)
        except (TypeError, ValueError):
            return "—"
        if n != n:   # NaN
            return "—"
        return f"£{n:.2f} (inc)"

    def units_and_gbp(units, val):
        if val is None:
            return "—"
        cash = gbp(val)
        if units is None:
            return cash
        return f"{int(float(units))} units · {cash}"

    cost = _num(eco.get("buy_cost_gbp"))
    target_buy = _num(eco.get("target_buy_cost_gbp"))     # BUY ceiling
    target_stretch = _num(eco.get("target_buy_cost_stretch_gbp"))  # tighter goal

    cost_label = "Your cost"
    cost_val = gbp(cost) if cost and cost > 0 else "— (no supplier yet)"

    units = bp.get("projected_30d_units")

    rows_html = [
        f'<tr><td class="econ-label">{cost_label}</td><td class="econ-value">{cost_val}</td></tr>',
    ]
    # The two target buys, ordered ambition → ceiling.
    if target_stretch is not None:
        rows_html.append(
            f'<tr><td class="econ-label">Aim for</td>'
            f'<td class="econ-value">{gbp(target_stretch)} <span class="econ-aside">— negotiate to this</span></td></tr>'
        )
    if target_buy is not None:
        rows_html.append(
            f'<tr><td class="econ-label">Don\'t exceed</td>'
            f'<td class="econ-value">{gbp(target_buy)} <span class="econ-aside">— absolute BUY ceiling</span></td></tr>'
        )
    if bp.get("order_qty_recommended") is not None:
        rows_html.append(
            f'<tr><td class="econ-label">Order qty</td>'
            f'<td class="econ-value">{int(bp.get("order_qty_recommended"))} units '
            f'(capital {gbp(bp.get("capital_required_gbp"))})</td></tr>'
        )
    rows_html.append(
        f'<tr><td class="econ-label">Projected 30d revenue</td>'
        f'<td class="econ-value">{units_and_gbp(units, bp.get("projected_30d_revenue_gbp"))}</td></tr>'
    )
    rows_html.append(
        f'<tr><td class="econ-label">Projected 30d profit</td>'
        f'<td class="econ-value">{units_and_gbp(units, bp.get("projected_30d_profit_gbp"))}</td></tr>'
    )
    if bp.get("payback_days") is not None:
        rows_html.append(
            f'<tr><td class="econ-label">Payback</td>'
            f'<td class="econ-value">{int(float(bp.get("payback_days")))} days</td></tr>'
        )
    return (
        '<section class="card-economics">'
        '<h4>Economics</h4>'
        '<table class="economics-grid"><tbody>' + "".join(rows_html) + '</tbody></table>'
        '</section>'
    )


def _render_supporting_metrics(row: dict) -> str:
    """Supporting data — the existing 7-row traffic-light table.

    Demoted to bottom of card. Still scannable but no longer the
    primary signal — the dimension bars + buyer's read carry that.
    """
    metrics = row.get("metrics") or []
    if not metrics:
        return ""
    rows_html = []
    for m in metrics:
        v = m.get("verdict") or "grey"
        cls = f"dot dot-{v}"
        rows_html.append(
            '<tr>'
            f'<td><span class="{cls}"></span></td>'
            f'<td class="metric-label">{_esc(m.get("label") or "")}</td>'
            f'<td class="metric-value">{_esc(m.get("value_display") or "")}</td>'
            f'<td class="metric-rationale">{_esc(m.get("rationale") or "")}</td>'
            '</tr>'
        )
    return (
        '<section class="card-supporting">'
        '<h4>Supporting metrics</h4>'
        '<table class="metrics"><tbody>' + "".join(rows_html) + '</tbody></table>'
        '</section>'
    )


def _render_engine_note(row: dict) -> str:
    """Small-print footer — engine's own verdict for cross-checking.

    When the engine's read disagrees with the analyst's, this lets
    the operator notice. Hidden visually until you scroll to it.
    """
    eng_verdict = row.get("engine_verdict") or "—"
    eng_conf = row.get("engine_verdict_confidence") or "—"
    eng_score = row.get("engine_opportunity_score")
    blockers = row.get("engine_blockers") or []
    flags = row.get("risk_flags") or []
    parts = [
        '<details class="engine-note">',
        '<summary>Engine cross-check</summary>',
        '<dl>',
        f'<dt>Engine verdict</dt><dd>{_esc(eng_verdict)} ({_esc(eng_conf)} confidence)</dd>',
    ]
    eng_score_n = _num(eng_score)
    if eng_score_n is not None:
        parts.append(f'<dt>Engine score</dt><dd>{int(eng_score_n)}/100</dd>')
    if blockers:
        parts.append(
            f'<dt>BUY blockers</dt><dd>{_esc("; ".join(blockers))}</dd>'
        )
    if flags:
        parts.append(
            f'<dt>Risk flags</dt><dd>{_esc(", ".join(flags))}</dd>'
        )
    parts.append('</dl></details>')
    return "".join(parts)


def _num(v: Any) -> float | None:
    if v is None:
        return None
    try:
        n = float(v)
    except (TypeError, ValueError):
        return None
    if n != n:
        return None
    return n


def _esc(s: Any) -> str:
    return _html.escape(str(s if s is not None else ""))


_CSS = """
:root {
  --buy: #27AE60; --negotiate: #E67E22; --source: #2980B9;
  --wait: #F1C40F; --skip: #95A5A6;
  --grey: #B0B0B0; --green: #27AE60; --amber: #E67E22; --red: #C0392B;
  --strong: #27AE60; --ok: #F1C40F; --weak: #C0392B;
}
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1B2A4A; max-width: 1280px; margin: 0 auto; padding: 1rem; background: #FAFBFC; }
.report-header { padding: 1rem; border-bottom: 1px solid #ddd; background: white; border-radius: 4px; }
.report-header h1 { margin: 0; }
.run-meta { color: #666; font-size: 0.9rem; }
.verdict-counts { margin-top: 0.5rem; }
.vat-note { color: #999; font-size: 0.8rem; margin-top: 0.3rem; }
.vc { display: inline-block; padding: 0.2rem 0.6rem; margin-right: 0.4rem; border-radius: 3px; font-size: 0.85rem; color: white; font-weight: bold; }
.vc-buy { background: var(--buy); }
.vc-negotiate { background: var(--negotiate); }
.vc-source { background: var(--source); }
.vc-wait { background: var(--wait); color: #1B2A4A; }
.vc-skip { background: var(--skip); }
.toc { padding: 1rem; background: #f8f9fa; border-radius: 4px; margin: 1rem 0; }
.toc h3 { margin-top: 0; }
.toc ul { margin: 0; padding-left: 1.2rem; font-size: 0.9rem; }
.empty-notice { padding: 2rem; text-align: center; color: #666; }
.verdict-section { margin: 2rem 0; }
.verdict-section h2 { padding-bottom: 0.3rem; border-bottom: 2px solid #eee; }
.card { background: white; border: 1px solid #e0e0e0; border-left: 5px solid #ddd; border-radius: 4px; padding: 1.2rem; margin: 1rem 0; max-width: 980px; box-shadow: 0 1px 3px rgba(0,0,0,0.04); }
.verdict-buy { border-left-color: var(--buy); }
.verdict-negotiate { border-left-color: var(--negotiate); }
.verdict-source { border-left-color: var(--source); }
.verdict-wait { border-left-color: var(--wait); }
.verdict-skip { border-left-color: var(--skip); }
.card section { padding: 0.6rem 0; border-top: 1px solid #f0f0f0; }
.card section:first-of-type, .card-header { border-top: none; }
.card h4 { margin: 0.3rem 0 0.5rem 0; font-size: 0.95rem; color: #34495E; }

/* Card header — image left, identity centre, verdict block right */
.card-header { display: grid; grid-template-columns: auto 1fr auto; gap: 1rem; align-items: center; padding-bottom: 1rem; border-bottom: 2px solid #f0f0f0; }
.card-image img { width: 110px; height: auto; max-width: 100%; object-fit: contain; }
.card-id-block .card-title { margin: 0 0 0.2rem 0; font-size: 1.15rem; }
.card-id { color: #666; font-size: 0.85rem; }
.card-verdict-block { text-align: right; }
.verdict-badge { font-size: 1.5rem; font-weight: bold; padding: 0.4rem 0.9rem; border-radius: 4px; background: #1B2A4A; color: white; display: inline-block; }
.verdict-buy .verdict-badge { background: var(--buy); }
.verdict-negotiate .verdict-badge { background: var(--negotiate); }
.verdict-source .verdict-badge { background: var(--source); }
.verdict-wait .verdict-badge { background: var(--wait); color: #1B2A4A; }
.verdict-skip .verdict-badge { background: var(--skip); }
.verdict-confidence { font-size: 0.8rem; color: #666; margin-top: 0.3rem; }
.card-score { font-size: 1.1rem; margin-top: 0.4rem; }
.card-score strong { font-size: 1.3rem; }

/* Dimension breakdown bars */
.dimensions { width: 100%; border-collapse: collapse; }
.dimensions td { padding: 0.4rem 0.5rem; vertical-align: middle; font-size: 0.9rem; }
.dim-name { width: 18%; font-weight: bold; color: #34495E; }
.dim-score { width: 8%; font-family: ui-monospace, monospace; font-size: 0.95rem; }
.dim-max { color: #999; font-size: 0.8em; }
.dim-bar-cell { width: 30%; padding: 0.4rem; }
.dim-bar { height: 8px; border-radius: 4px; transition: width 0.3s; }
.dim-bar.dim-strong { background: var(--strong); }
.dim-bar.dim-ok { background: var(--ok); }
.dim-bar.dim-weak { background: var(--weak); }
.dim-rationale { color: #555; font-size: 0.85rem; }

/* Buyer's read — prominent narrative */
.card-buyers-read { background: #F4F8FB; padding: 0.8rem 1rem !important; border-radius: 4px; margin-top: 0.5rem; }
.buyers-narrative { margin: 0 0 0.5rem 0; line-height: 1.55; font-size: 0.98rem; }
.buyers-action { margin: 0; font-size: 0.9rem; color: #34495E; }

/* Direction arrows */
.dir-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; max-width: 500px; }
.dir-cell { text-align: center; padding: 0.5rem; background: #f8f9fa; border-radius: 4px; }
.dir-label { font-size: 0.8rem; color: #666; }
.dir-arrow { font-size: 2rem; font-weight: bold; line-height: 1; margin-top: 0.2rem; }
.arrow-up { color: var(--green); }
.arrow-down { color: var(--red); }
.arrow-flat { color: #999; }
.arrow-unknown { color: var(--grey); }
.dir-story { margin-top: 0.6rem; font-size: 0.9rem; color: #555; font-style: italic; }

/* Economics */
.economics-grid { width: 100%; border-collapse: collapse; font-size: 0.95rem; }
.economics-grid td { padding: 0.4rem; vertical-align: top; }
.econ-label { color: #666; font-size: 0.85rem; width: 30%; }
.econ-value { font-weight: bold; }
.econ-aside { color: #999; font-weight: normal; font-size: 0.85em; }

/* Supporting metrics */
.metrics { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
.metrics td { padding: 0.25rem 0.5rem; vertical-align: middle; }
.dot { width: 12px; height: 12px; border-radius: 50%; display: inline-block; }
.dot-green { background: var(--green); }
.dot-amber { background: var(--amber); }
.dot-red { background: var(--red); }
.dot-grey { background: transparent; border: 1.5px solid var(--grey); }
.metric-label { width: 25%; color: #555; }
.metric-value { font-weight: bold; width: 18%; font-family: ui-monospace, monospace; }
.metric-rationale { color: #777; font-size: 0.82rem; }

/* Engine cross-check (small-print footer) */
.engine-note { font-size: 0.85rem; color: #666; margin-top: 0.5rem; }
.engine-note summary { cursor: pointer; padding: 0.3rem 0; }
.engine-note dl { margin: 0.4rem 0 0 1rem; }
.engine-note dt { font-weight: bold; color: #555; }
.engine-note dd { margin: 0 0 0.4rem 1rem; }

footer { margin-top: 2rem; color: #999; font-size: 0.85rem; text-align: center; }

@media print {
  .toc { display: none; }
  .card { page-break-inside: avoid; box-shadow: none; }
  body { background: white; }
}
"""
